# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-29 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belttest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='alias',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='doh',
            new_name='dob',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='email@email.com', max_length=255),
            preserve_default=False,
        ),
    ]
